version: 2
jobs:
  production_build:
    docker:
      - image: cibuilds/hugo:0.27
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
  staging_build:
    docker:
      - image: cibuilds/hugo:0.27
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=staging hugo -v -s ~/project
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
  staging_deploy:
    docker:
      - image: cibuilds/aws
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Upload to Staging - skip static files"
          command: aws s3 sync --acl "public-read" ~/project/public/ s3://${STAGING_BUCKET}/ --exclude 'images' --exclude 'sass' --exclude 'fonts' --exclude 'js'
      - run:
          name: "Copy and cache static files"
          command: |
            aws s3 sync --cache-control "max-age=2592000" --acl "public-read" ~/project/public/images/ s3://${STAGING_BUCKET}/images/
            aws s3 sync --cache-control "max-age=2592000" --acl "public-read" ~/project/public/css/ s3://${STAGING_BUCKET}/css/
            aws s3 sync --cache-control "max-age=2592000" --acl "public-read" ~/project/public/js/ s3://${STAGING_BUCKET}/js/
            aws s3 sync --cache-control "max-age=2592000" --acl "public-read" ~/project/public/sass/ s3://${STAGING_BUCKET}/sass/
            aws s3 sync --cache-control "max-age=2592000" --acl "public-read" ~/project/public/fonts/ s3://${STAGING_BUCKET}/fonts/
  prod_deploy:
    docker:
      - image: cibuilds/aws
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Upload to Production"
          command: aws s3 sync ~/project/public --region $REGION s3://${BUCKET}/ --delete
      - run:
          name: "Invalidate CloudFront"
          command: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - staging_build:
          filters:
            branches:
              only: staging
      - production_build:
          filters:
            branches:
              only: production
      - staging_deploy:
          requires:
            - staging_build
          filters:
            branches:
              only: staging
      - prod_deploy:
          requires:
            - production_build
          filters:
            branches:
              only: production
