version: 2
jobs:
  production_build:
    docker:
      - image: cibuilds/hugo:0.27
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s ~/project
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
  staging_build:
    docker:
      - image: cibuilds/hugo:0.27
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=staging hugo -v -s ~/project
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
  staging_deploy:
    docker:
      - image: golang
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "install s3deploy"
          command: go get -v github.com/bep/s3deploy
      - run:
          name: "Upload to Staging"
          command: s3deploy -v -force -config=.s3deploy.yml -source=public/ -region=$STAGING_REGION -bucket=${STAGING_BUCKET}/
  prod_deploy:
    docker:
      - image: golang
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "install s3deploy"
          command: go get -v github.com/bep/s3deploy
      - run:
          name: "Upload to Staging"
          command: s3deploy -v -force -config=.s3deploy.yml -source=public/ -region=$REGION -bucket=$BUCKET/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - staging_build:
          filters:
            branches:
              only: staging
      - production_build:
          filters:
            branches:
              only: production
      - staging_deploy:
          requires:
            - staging_build
          filters:
            branches:
              only: staging
      - prod_deploy:
          requires:
            - production_build
          filters:
            branches:
              only: production
