version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.27
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project
      - persist_to_workspace:
          root: ~/project
          paths:
            - public
  deploy:
    docker:
      - image: cibuilds/aws
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Upload to S3"
          command: aws s3 sync ~/project/public --region us-west-1 s3://${BUCKET}/ --delete
      - run:
          name: "Invalidate CloudFront"
          command: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
