baseurl = "//cszsa.com"
title = "ComedySportz San Antonio"
theme = "cszsa"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  featured_show = "tickets"
  title = "ComedySportz San Antonio"
  description = '<!--[-->Fast-paced improvisational comedy, played as a sport. Comedy for everyone!<!--]-->'
  meta_description = "ComedySportz San Antonio is the only family friendly comedy in San Antonio. Bring your kids, bring Grandma. We won't offend anyone. We promise."
  logoimage = "/images/cszshield.png"
  copyright = "CSz San Antonio"
  seo_description = "ComedySportz San Antonio Improv is the only family friendly comedy in San Antonio. Bring your kids, bring Grandma. We won't offend anyone we promise."
  keywords = ["San Antonio Improv", "improv san antonio", "Comedy", "Comedy in San Antonio", "Improv", "Improvisational theater", "family friendly", "comedy classes", "corporate training", "team building"]
  images = ["//cszsa.com/images/sanantonioimprovcomedysportz.jpg", "//cszsa.com/images/sanantonioimprovcomedy.jpg", "//cszsa.com/images/sanantoniocomedyimprov-show.JPG"]

# Start SEO Stuff

  [params.seo]
    github      = "albush/cszsa.com"
    facebook        = "ComedySportzSanAntonio"
    facebook_admin  = "54292585762"  # This needs to be a page admin to get domain insights
    twitter     = "CSzSanAntonio"
    twitter_domain  = "cszsa.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram       = "cszsa"


# End SEO Stuff

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "//twitter.com/CSzSanAntonio"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "//facebook.com/ComedySportzSanAntonio/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "//www.instagram.com/cszsa/"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "ComedySportz San Antonio"

  [params.meta]
    facebook		= "ComedySportzSanAntonio"
    #facebook_admin	= "17807199"  # This needs to be a page admin to get domain insights
    twitter		= "CSzSanAntonio"
    twitter_domain	= "cszsa.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram		= "cszsa"
