baseURL = "https://cszsa.com"
customCSS = ["", ""]
enableEmoji = true
googleAnalytics = "UA-117320918-1"
languageCode = "en-us"
theme = "alpha-csz"
title = "ComedySportz San Antonio"
subtitle = "Comedy for Everyone"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Buy Tickets"
url = "/shows"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "About"
url = "/#"
weight = 3
[[menu.main]]
name = "About CSz San Antonio"
parent = "About"
url = "/about"
weight = 1
[[menu.main]]
name = "Reviews"
parent = "About"
url = "/reviews"
weight = 2
[[menu.main]]
name = "Shows"
url = "#"
weight = 4
[[menu.main]]
name = "ComedySportz"
parent = "Shows"
url = "/comedysportz"
weight = 1
[[menu.main]]
name = "After Dark"
parent = "Shows"
url = "/afterdark"
weight = 2
[[menu.main]]
name = "Groups and Events"
url = "/"
weight = 5
[[menu.main]]
name = "Private Shows"
parent = "Groups and Events"
url = "/privateshows"
weight = 1
[[menu.main]]
name = "Classes"
url = "/training"
weight = 4
[[menu.main]]
name = "Team Building"
parent = "Groups and Events"
url = "/teambuilding"
weight = 2
[[menu.main]]
name = "School Assemblies"
parent = "Groups and Events"
url = "/school-assemblies"
weight = 2
[[menu.main]]
name = "Contact"
parent = "About"
url = "/contact"
weight = 2
[[menu.main]]
name = "Players"
parent = "Shows"
url = "/team"
weight = 3
[[menu.main]]
name = "Match Recaps"
parent = "Shows"
url = "/matches"
weight = 4
[params]
author = "Alan Bush"
subtitle = "Comedy for Everyone"
description = "ComedySportz Improv Comedy in San Antonio. Funny for Everyone!"
title = "ComedySportz San Antonio"
images = ["images/comedysportzsanantonio.jpg"]
[params.contact]
confirm_page = "/contact_thanks"
formspree_email = "info@cszsa.com"
service = "formspree"
[params.urgent]
content = "covid19.md"
[params.special_event]
#comment out special event section if no events are scheduled
events = ["training"]
description = "Our next Improv 101 & 201 Classes start on Sunday April 5th"
[params.awards]
#comment out awards section if no awards are featured
image = "images/familyenterainmentwreath.png"
description = "Thank you Loyal Fans for voting us for the best family entertainment in San Antonio!"
[params.footer]
copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)", "Design: [HTML5 UP](//html5up.net/alpha)", "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)", "[Privacy Policy](/privacy)"]
[params.landing.CTA]
heading = "Get in touch!"
message = "We'd love to hear from you."
[params.landing.banner]
image = "images/bg1.jpg"
[[params.landing.banner.button]]
text = "Get Your Tickets"
type = "special"
url = "https://squareup.com/store/CSzSA/"
[[params.landing.banner.button]]
text = "What's it all about?"
type = "special"
url = "#feature-images"
[params.landing.feature_icons]
enable = false
[[params.landing.feature_icons.tile]]
accent = "1"
icon = "fa-ticket-alt"
icon_pack = "fas"
text = "Family-friendly shows every weekend."
title = "Improv Comedy"
[[params.landing.feature_icons.tile]]
accent = "2"
icon = "fa-theater-masks"
icon_pack = "fas"
text = "Learn about improv from our ComedySportz Players."
title = "Classes"
[[params.landing.feature_icons.tile]]
accent = "5"
icon = "fa-school"
icon_pack = "fas"
text = "We've got the perfect comedy show for all ages."
title = "School Assemblies"
[[params.landing.feature_icons.tile]]
accent = "3"
icon = "fa-users"
icon_pack = "fas"
text = "We'll take our show to your event. Perfect for company parties, school assemblies, birthday parties, etc."
title = "Group Events"
[params.landing.feature_images]
enable = true
[[params.landing.feature_images.tile]]
button_text = "See Our Current Shows"
image = "images/sanantonioimprovcomedysportz.jpg"
logo = "images/CSz_Entertainment_long_COLOR.png"
text = "CSz's entertainment began with ComedySportz®, our flagship show, and we're proud to bring it to San Antonio. Read more about what a ComedySportz match is like at our FAQ."
title = "Corporate Training & Team Building"
url = "/shows"
[[params.landing.feature_images.tile]]
button_text = "Book Something Awesome"
logo = "images/CSz_Groups_long_COLOR.png"
image = "images/events_1.jpg"
text = "We're here to make your job easier. Whether it's a block of seats at a ComedySportz® Match, a Private Event just for your group or a customized improv workshop, CSz San Antonio has your needs in mind. We know what it takes on your end, and we're willing to work with you to make your tour, event or outing successful. Visit our Groups & Events page to learn more. Get a price quote emailed to you within 24 hours!"
title = "Private Shows"
url = "/privateshows"
[[params.landing.feature_images.tile]]
button_text = "Browse List of Possibilities"
image = "images/comedysportzcorporatetraining.jpg"
logo = "images/CSz_Business_long_COLOR.png"
text = "From valuable and customizable training using Applied Improvisation, to the entertaining and hilarious ComedySportz® at your event, to projects where you need the talent and funny, CSz San Antonio can help make you look like a genius. Visit our CSz Business page to learn how to take your team to the next level."
title = "Corporate Training & Team Building"
url = "/teambuilding"
[[params.landing.feature_images.tile]]
button_text = "Start Learning"
image = "images/improv301.jpg"
logo = "images/CSz_Education_long_COLOR.png"
text = "CSz improv and applied improv classes are a fun, supportive way to learn improvisational thinking and gain self-confidence. Don't be fooled into thinking improv is just for performers - many of our students use improv to develop business soft-skills, and communicate better - and they meet other cool people! We're constantly adding more training series and drop-in workshops for adults as well as high school students and younger. Visit our CSz Education page to see the latest classes being offered."
title = "Corporate Training & Team Building"
url = "/training"
[params.landing.services]
text = "Family friendly improv comedy every Friday and Saturday at 7:30pm. Adults only show at 10pm Saturday. [11950 STARCREST DR #210, SAN ANTONIO, TX 78247](https://goo.gl/maps/KKWiA927iAT2)"
title = "Live Local Comedy Shows Every Friday and Saturday"
[params.map]
latitude = "29.549099"
longitude = "-98.462961"
zoom = "14"
[[params.links]]
icon = "fa-twitter"
icon_pack = "fab"
link = "//twitter.com/CSzSanAntonio"
service = "Twitter"
[[params.links]]
icon = "fa-facebook"
icon_pack = "fab"
link = "//facebook.com/ComedySportzSanAntonio/"
service = "Facebook"
[[params.links]]
icon = "fa-instagram"
icon_pack = "fab"
link = "//www.instagram.com/cszsanantonio/"
service = "Instagram"
