baseURL = "/"
customCSS = ["", ""]
enableEmoji = true
googleAnalytics = ""
languageCode = "en-us"
theme = "alpha-csz"
title = "ComedySportz San Antonio"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Buy Tickets"
url = "/buytickets"
weight = 2
[[menu.main]]
name = "About"
url = "/"
weight = 3
[[menu.main]]
name = "About ComedySportz"
parent = "About"
url = "/about"
weight = 1
[[menu.main]]
name = "Reviews"
parent = "About"
url = "/reviews"
weight = 2
[[menu.main]]
name = "Shows"
url = "#"
weight = 4
[[menu.main]]
name = "ComedySportz"
parent = "Shows"
url = "/comedysportz"
weight = 1
[[menu.main]]
name = "After Dark"
parent = "Shows"
url = "/afterdark"
weight = 2
[[menu.main]]
name = "Groups and Events"
url = "/"
weight = 5
[[menu.main]]
name = "Private Shows"
parent = "Groups and Events"
url = "/privateshows"
weight = 1
[[menu.main]]
name = "Team Building"
parent = "Groups and Events"
url = "/teambuilding"
weight = 2
[[menu.main]]
name = "School Assemblies"
parent = "Groups and Events"
url = "/school-assemblies"
weight = 2
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[params]
author = "Alan Bush"
subtitle = "Family Friendly Improv Comedy"
title = "ComedySportz San Antonio"
[params.contact]
confirm_page = "/contact_thanks"
formspree_email = "info@cszsa.com"
service = "formspree"
[params.footer]
copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)", "Design: [HTML5 UP](//html5up.net/alpha)", "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"]
[params.landing.CTA]
heading = "Get in touch!"
message = "We'd love to hear from you."
[params.landing.banner]
image = "images/header-bg.jpg"
[[params.landing.banner.button]]
text = "Buy Tickets"
type = "special"
url = "https://squareup.com/store/CSzSA/"
[[params.landing.banner.button]]
text = "Special Events and Classes"
url = "#feature-images"
[params.landing.feature_icons]
enable = false
[[params.landing.feature_icons.tile]]
accent = "1"
icon = "fa-ticket-alt"
icon_pack = "fas"
text = "Family-friendly shows every weekend."
title = "Improv Comedy"
[[params.landing.feature_icons.tile]]
accent = "2"
icon = "fa-theater-masks"
icon_pack = "fas"
text = "Learn about improv from our ComedySportz Players."
title = "Classes"
[[params.landing.feature_icons.tile]]
accent = "5"
icon = "fa-school"
icon_pack = "fas"
text = "We've got the perfect comedy show for all ages."
title = "School Assemblies"
[[params.landing.feature_icons.tile]]
accent = "3"
icon = "fa-users"
icon_pack = "fas"
text = "We'll take our show to your event. Perfect for company parties, school assemblies, birthday parties, etc."
title = "Group Events"
[params.landing.feature_images]
enable = true
[[params.landing.feature_images.tile]]
button_text = "Learn More"
image = "images/comedysportzprivateshows.jpg"
text = "It's a ComedySportz show, just for you. Your place or ours, you bring the suggestions, we'll bring the comedy."
title = "Private Shows"
url = "/privateshows"
[[params.landing.feature_images.tile]]
button_text = "Learn More"
image = "images/comedysportzcorporatetraining.jpg"
text = "CSz Business Training. Because work is more than numbers."
title = "Corporate Training & Team Building"
url = "/teambuilding"
[[params.landing.feature_images.tile]]
button_text = "Learn More"
image = "images/comedysportzcorporatetraining.jpg"
text = "CSz Business Training. Because work is more than numbers."
title = "Corporate Training & Team Building"
url = "/teambuilding"
[params.landing.services]
text = "Family friendly improv comedy every Friday and Saturday at 7:30pm. Adults only show at 10pm Saturday. [11950 STARCREST DR #210, SAN ANTONIO, TX 78247](https://goo.gl/maps/KKWiA927iAT2)"
title = "Weekly Improv Shows"
[params.map]
latitude = "29.549099"
longitude = "-98.462961"
zoom = "14"
[[params.links]]
icon = "fa-twitter"
icon_pack = "fab"
link = "//twitter.com/CSzSanAntonio"
service = "Twitter"
[[params.links]]
icon = "fa-facebook"
icon_pack = "fab"
link = "//facebook.com/ComedySportzSanAntonio/"
service = "Facebook"
[[params.links]]
icon = "fa-instagram"
icon_pack = "fab"
link = "//www.instagram.com/cszsa/"
service = "Instagram"
