baseurl = "https://cszsa.com"
title = "ComedySportz San Antonio"
theme = "cszsa"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
googleAnalytics = "UA-117320918-1"

[params]
  # special_event = ""
  special_class = ["improv101", "improv201"]
  class_description = "Our next round of Improv 101 classes are forming now for Saturdays, starting July 21st; 201 classes will be on Sundays, starting July 15th."
  featured_show = ["cszfri", "cszsat", "adreturn"]
  title = "ComedySportz San Antonio"
  description = '<!--[-->ComedySportz San Antonio is the only family friendly comedy in San Antonio. Bring your kids, bring Grandma. We won&#39;t offend anyone. We promise.<!--]-->'
  meta_description = "ComedySportz San Antonio is the only family friendly comedy in San Antonio. Bring your kids, bring Grandma. We won't offend anyone. We promise."
  logoimage = "/images/cszshield.png"
  copyright = "CSz San Antonio"
  seo_description = "ComedySportz San Antonio Improv is the only family friendly comedy in San Antonio. Bring your kids, bring Grandma. We won't offend anyone we promise."
  keywords = ["San Antonio Improv", "improv san antonio", "Comedy", "Comedy in San Antonio", "Improv", "Improvisational theater", "family friendly", "comedy classes", "corporate training", "team building"]
  images = ["https://cszsa.com/images/sanantonioimprovcomedysportz.jpg", "https://cszsa.com/images/sanantonioimprovcomedy.jpg", "https://cszsa.com/images/sanantoniocomedyimprov-show.JPG"]

# Start SEO Stuff

  [params.seo]
    github      = "albush/cszsa.com"
    facebook        = "ComedySportzSanAntonio"
    facebook_admin  = "54292585762"  # This needs to be a page admin to get domain insights
    twitter     = "CSzSanAntonio"
    twitter_domain  = "cszsa.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram       = "cszsa"


# End SEO Stuff

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/CSzSanAntonio"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://facebook.com/ComedySportzSanAntonio/"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/cszsa/"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "ComedySportz San Antonio"

  [params.meta]
    facebook		= "ComedySportzSanAntonio"
    #facebook_admin	= "17807199"  # This needs to be a page admin to get domain insights
    twitter		= "CSzSanAntonio"
    twitter_domain	= "cszsa.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram		= "cszsa"
