---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: data/shows
  label: Shows
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: heading
  label: Content
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Temporary Events
- type: directory
  path: data/classes
  label: Classes
  create: all
  match: "**/*"
  new_doc_ext: yml
  templates:
  - improv101-yml
- type: document
  path: README-FORESTRY.md
  label: Help
  read_only: true
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.48'
