---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: README-FORESTRY.md
  label: Help
  read_only: true
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Players
- type: directory
  path: data/players
  label: Player Bios
  create: documents
  match: "**/*"
  new_doc_ext: yml
- type: directory
  path: content/team
  label: Player Shows
  create: documents
  match: "**/*"
- type: heading
  label: Matches
- type: directory
  path: content/shows
  label: Upcoming Matches
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: content/matches
  label: Match Recaps
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Temporary Events
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.48'
