# theme.toml template for a Hugo theme
# See //github.com/spf13/hugoThemes#themetoml for an example

name = "Dimension"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/sethmacleod/dimension/blob/master/LICENSE.md"
description = "Dimension is a single page and responsive site template using modals as pages."
homepage = "//github.com/sethmacleod/dimension"
tags = ["responsive", "personal", "portfolio", "multilingual"]
features = ["responsive", "multilingual"]
min_version = 0.18

[author]
  name = "Seth MacLeod"
  homepage = "//www.sethmacleod.com/"

# If porting an existing theme
[original]
  name = "@ajlkn"
  homepage = "//html5up.net/dimension"
  repo = ""
